package main

import (
	"flag"
	"fmt"
	"io"
	"log"
	"os"

	"github.com/apex/rpc/generators/swiftclient"
	"github.com/apex/rpc/schema"
)

func main() {
	path := flag.String("schema", "schema.json", "Path to the schema file")
	client := flag.String("client", "Client", "Name for the client")
	flag.Parse()

	s, err := schema.Load(*path)
	if err != nil {
		log.Fatalf("error: %s", err)
	}

	err = generate(os.Stdout, s)
	if err != nil {
		log.Fatalf("error: %s", err)
	}
}

// generate implementation.
func generate(w io.Writer, s *schema.Schema, client string) error {
	out := fmt.Fprintf
	out(w, "// Do not edit, this file was generated by github.com/apex/rpc.\n\n")

	err := swiftclient.Generate(w, s, client)
	if err != nil {
		return fmt.Errorf("generating client: %w", err)
	}

	return nil
}
